# Generated by Django 5.2.8 on 2025-11-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0003_alter_car_category_alter_car_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
