# Generated by Django 5.2.8 on 2025-11-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0006_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('paypal', 'PayPal'), ('crypto', 'Crypto')], default='card', max_length=20),
        ),
    ]
