# Generated by Django 5.2.8 on 2025-11-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0007_remove_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
