# Generated by Django 5.2.8 on 2025-11-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0008_booking_payment_status_alter_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='crypto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
